name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: CompatHelper
        uses: JuliaRegistries/CompatHelper.jl@smann/compathelper-action
